repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: pretty-format-json
      args:
          - "--autofix"
          - "--indent=4"
          - "--no-sort-keys"
  - repo: https://github.com/jsh9/pydoclint
    rev: 0.4.1
    hooks:
      - id: pydoclint