channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - conda-forge::datasets==2.19.1
  - conda-forge::nltk==3.8.1
  - conda-forge::numpy==1.26.4
  - conda-forge::pytorch-lightning==2.2.2
  - conda-forge::scikit-learn==1.4.2
  - conda-forge::spacy==3.7.3
  - pytorch::pytorch==2.2.2
  - conda-forge::transformers==4.40.2
  - pip:
    - fastapi>=0.86.0
    - loguru>=0.7.2
    - python-json-logger>=2.0.7,<3.0.0
    - tqdm>=4.64.0,<5
    - uvicorn>=0.12.0,<0.19.0