extend-exclude = ["training"]
force-exclude = true

[lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
ignore = [
  "F722", # Ruff incorrectly picks up ndarrays as recursive types
  "D10", # Allow missing docstrings
  "D200", # One-line docstring should fit on one line
  "D205", # 1 blank line required between summary line and description
  "D212", # Multi-line docstring summary should start at the first line
  "D415", # First line should end with a period, question mark, or exclamation point
]
select = [
  "E4",
  "E7",
  "E9",
  "F",
  "I",
  "D", # Enable docstring checks
  "D213", # Multi-line docstring summary should start at the second line (not part of google convention)
]

[lint.pydocstyle]
convention = "google"